a=input('Enter the first number: ')
b=input('Enter the second number: ')
a=int(a)
b=int(b)
print("Addition: "+ str(a+b))
print("Subtraction: "+ str(a-b))
print("Multiplication: "+ str(a*b))
print("Division: "+ str(a/b))
